### ISSUE TITLE
mbx fails with ACS 4.16/main due to python3/pip3 issue

### ISSUE THREAD

**Issue by rhtyd** [shapeblue/mbx#14]
```
> mbx launch qa1-cs416-snap-a157ebd8-kvm
MonkeyBox 🐵 v0.1
+ echo 'Launching CloudStack Zone in the environment:'
Launching CloudStack Zone in the environment:
+ env=qa1-cs416-snap-a157ebd8-kvm
+ '[' -z qa1-cs416-snap-a157ebd8-kvm ']'
++ echo qa1-cs416-snap-a157ebd8-kvm
++ sed 's/^qa//g'
++ sed 's/-.*$//g'
+ id=1
+ echo 'Generating marvin config for env ID 1'
Generating marvin config for env ID 1
++ getent hosts qa1-cs416-snap-a157ebd8-kvm-mgmt1
++ awk '{ print $1 }'
+ msip=172.20.0.144
+ sshpass -p P@ssword123 scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no /export/monkeybox/boxes/qa1-cs416-snap-a157ebd8-kvm/marvin.cfg root@172.20.0.144:/marvin/
Warning: Permanently added '172.20.0.144' (ECDSA) to the list of known hosts.
+ sshpass -p P@ssword123 scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no /export/monkeybox/files/smoketests.sh root@172.20.0.144:/marvin/
Warning: Permanently added '172.20.0.144' (ECDSA) to the list of known hosts.
+ sshpass -p P@ssword123 scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no /export/monkeybox/files/result.py root@172.20.0.144:/marvin/
Warning: Permanently added '172.20.0.144' (ECDSA) to the list of known hosts.
+ nc -vzw 5 172.20.0.144 8096
Connection to 172.20.0.144 8096 port [tcp/*] succeeded!
+ sshpass -p P@ssword123 ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@172.20.0.144 systemctl start cloudstack-usage
Warning: Permanently added '172.20.0.144' (ECDSA) to the list of known hosts.
+ sshpass -p P@ssword123 ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@172.20.0.144 'mysql -u root --execute="UPDATE cloud.service_offering set ram_size=512 where vm_type='\''consoleproxy'\'';"'
Warning: Permanently added '172.20.0.144' (ECDSA) to the list of known hosts.
+ echo 'Management server is UP now, launching data center now'
Management server is UP now, launching data center now
+ sshpass -p P@ssword123 ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@172.20.0.144 'python /usr/lib/python2.7/site-packages/marvin/deployDataCenter.py -i /marvin/marvin.cfg || python3 /usr/local/lib/python3.6/site-packages/marvin/deployDataCenter.py -i /marvin/marvin.cfg'
Warning: Permanently added '172.20.0.144' (ECDSA) to the list of known hosts.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/marvin/deployDataCenter.py", line 34, in <module>
    from marvin.lib.utils import (random_gen)
  File "/usr/lib/python2.7/site-packages/marvin/lib/utils.py", line 30, in <module>
    import urllib.parse
ImportError: No module named parse
python3: can't open file '/usr/local/lib/python3.6/site-packages/marvin/deployDataCenter.py': [Errno 2] No such file or directory

```

**Comment by Pearl1594** [comment]
@rhtyd I believe your fix - https://github.com/shapeblue/mbx/commit/846f641048f0b70ebb905f6058786f568d6ed975 has addressed this issue
